In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("digital_payment_behavior_clustering_dataset.csv")

In [5]:
df.head()

,user_id,city,device_type,kyc_level,account_age_months,account_age_band,active_days_per_month,transactions_per_day,monthly_transaction_count,avg_transaction_amount,...,night_txn_ratio,weekend_txn_ratio,session_count,app_open_frequency,avg_session_duration_min,avg_gap_between_txn_hours,spend_volatility,avg_balance_before_txn,cashback_usage_ratio,suspicious_activity_score
0,UPI00001,Mumbai,Android,Minimum,28,2y+,17,5.12,109,246.96,...,0.073,0.321,66,111,2.14,3.72,0.359,5464.53,0.333,26.91
1,UPI00002,Chennai,Android,Premium,11,6-12m,14,1.55,20,517.36,...,0.113,0.292,33,50,4.18,31.47,0.476,2894.69,0.327,13.03
2,UPI00003,Pune,Android,Premium,31,2y+,17,3.96,54,894.50,...,0.102,0.365,31,41,6.20,12.27,0.409,7560.72,0.279,32.01
3,UPI00004,Chennai,Android,Minimum,14,1-2y,11,9.99,110,1358.09,...,0.614,0.598,41,117,9.17,4.02,0.535,47098.46,0.373,77.72
4,UPI00005,Ahmedabad,Android,Full,29,2y+,16,11.99,167,493.71,...,0.553,0.448,44,84,7.42,3.23,0.847,55402.11,0.310,78.22

## Question 1
**How many unique users are present in the dataset?**

In [6]:
df['user_id'].nunique()

5000

## Question 2
**Are there any missing values or duplicate records?**

In [7]:
print(df.isnull().sum())
print('Duplicate rows:',df.duplicated().sum())

user_id                      0
city                         0
device_type                  0
kyc_level                    0
account_age_months           0
account_age_band             0
active_days_per_month        0
transactions_per_day         0
monthly_transaction_count    0
avg_transaction_amount       0
max_transaction_amount       0
total_monthly_spend          0
merchant_txn_ratio           0
peer_txn_ratio               0
merchant_count_month         0
peer_count_month             0
failed_transactions          0
failed_txn_ratio             0
refund_requests              0
refund_ratio                 0
night_txn_ratio              0
weekend_txn_ratio            0
session_count                0
app_open_frequency           0
avg_session_duration_min     0
avg_gap_between_txn_hours    0
spend_volatility             0
avg_balance_before_txn       0
cashback_usage_ratio         0
suspicious_activity_score    0
dtype: int64
Duplicate rows: 0

## Question 3
**Is each user_id unique?**

In [9]:
df['user_id'].is_unique

True

## Question 4
**How many users belong to each city?**

In [10]:
df['city'].value_counts()

city
Pune         643
Hyderabad    636
Delhi        632
Bengaluru    632
Mumbai       627
Ahmedabad    621
Chennai      606
Kolkata      603
Name: count, dtype: int64

## Question 5
**What is the distribution of users across Android and iOS devices?**

In [8]:
df['device_type'].value_counts()

device_type
Android    3871
iOS        1129
Name: count, dtype: int64

## Question 6
**How many users have Minimum, Full and Premium KYC levels?**

In [11]:
df["kyc_level"].value_counts()

kyc_level
Full       2879
Minimum    1423
Premium     698
Name: count, dtype: int64

## Question 7
**What is the distribution of users across the different account-age bands?**

In [12]:
df['account_age_band'].value_counts()

account_age_band
1-2y     2241
2y+      1201
6-12m     882
0-6m      676
Name: count, dtype: int64

## Question 8
**What are the minimum, maximum and average values of account_age_months**

In [13]:
df['account_age_months'].agg(['min','max','mean'])

min      1.000
max     58.000
mean    17.557
Name: account_age_months, dtype: float64

## Question 9
**Does account_age_band correctly correspond to account_age_months?**

## Question 10
**How do transaction activity and spending differ across KYC levels?**

In [14]:
df.groupby('kyc_level')[['monthly_transaction_count','total_monthly_spend']].mean()

           monthly_transaction_count  total_monthly_spend
kyc_level
Full                       86.377562         71639.020646
Minimum                    86.205903         67172.370562
Premium                    86.597421         68481.068095

## Question 11
**What is the average number of active days per month?**

In [15]:
df['active_days_per_month'].mean()

np.float64(17.1322)

## Question 12
**What is the distribution of monthly_transaction_count?**

In [16]:
df['monthly_transaction_count'].describe()

count    5000.000000
mean       86.359400
std        68.038231
min         1.000000
25%        32.000000
50%        75.000000
75%       127.000000
max       440.000000
Name: monthly_transaction_count, dtype: float64

## Question 13
**Which users complete the highest number of monthly transactions?**

In [17]:
df.nlargest(10,'monthly_transaction_count')[['user_id','monthly_transaction_count']]

       user_id  monthly_transaction_count
2656  UPI02657                        440
3394  UPI03395                        411
2099  UPI02100                        403
4907  UPI04908                        401
3350  UPI03351                        385
1516  UPI01517                        364
289   UPI00290                        363
1654  UPI01655                        343
2083  UPI02084                        343
1557  UPI01558                        341

## Question 14
**Which users have the highest transactions_per_day?**

In [18]:
df.nlargest(10,'transactions_per_day')[['user_id','transactions_per_day']]

       user_id  transactions_per_day
273   UPI00274                 20.11
4237  UPI04238                 19.78
278   UPI00279                 19.65
3394  UPI03395                 19.18
3725  UPI03726                 19.11
2656  UPI02657                 19.00
663   UPI00664                 18.69
1889  UPI01890                 18.31
2954  UPI02955                 18.07
685   UPI00686                 18.00

## Question 15
**How is active_days_per_month related to monthly_transaction_count?**

In [19]:
df[['active_days_per_month','monthly_transaction_count']].corr()

                           active_days_per_month  monthly_transaction_count
active_days_per_month                   1.000000                   0.702211
monthly_transaction_count               0.702211                   1.000000

## Question 16
**Which users perform many transactions within relatively few active days?**

In [20]:
df[['active_days_per_month','monthly_transaction_count']].corr()

                           active_days_per_month  monthly_transaction_count
active_days_per_month                   1.000000                   0.702211
monthly_transaction_count               0.702211                   1.000000

## Question 17
**Which users are active frequently but complete relatively few transactions?**

In [21]:
df.assign(ratio=df.monthly_transaction_count/df.active_days_per_month).nlargest(10,'ratio')[['user_id','ratio']]

       user_id      ratio
3725  UPI03726  20.909091
4237  UPI04238  20.000000
685   UPI00686  19.687500
273   UPI00274  19.500000
278   UPI00279  19.444444
663   UPI00664  18.909091
2396  UPI02397  18.857143
2954  UPI02955  18.705882
3394  UPI03395  17.869565
1889  UPI01890  17.833333

## Question 18
**What is the average gap between transactions for different levels of transaction activity?**

## Question 19
**Which users have unusually short gaps between consecutive transactions?**

In [68]:
df.nsmallest(10,'avg_gap_between_transactions')[['user_id','avg_gap_between_transactions']]

KeyError: 'avg_gap_between_transactions'

## Question 20
**How does transaction activity differ across account-age bands?**

In [52]:
df.groupby("account_age_band")["monthly_transaction_count"].mean()

account_age_band
0-6m     89.343195
1-2y     86.827309
2y+      86.867610
6-12m    82.191610
Name: monthly_transaction_count, dtype: float64

## Question 21
**What are the average, minimum and maximum values of avg_transaction_amount?**

In [24]:
df["avg_transaction_amount"].agg(['min','max','mean'])

min       20.000000
max     7057.300000
mean     953.655104
Name: avg_transaction_amount, dtype: float64

## Question 22
**Which users have the highest max_transaction_amount?**

In [29]:
df.nlargest(10,'max_transaction_amount')[['user_id','max_transaction_amount']]

       user_id  max_transaction_amount
2201  UPI02202                22554.74
4024  UPI04025                20400.60
4294  UPI04295                20174.47
708   UPI00709                20105.95
2811  UPI02812                20080.83
4579  UPI04580                19161.80
1972  UPI01973                18589.06
2129  UPI02130                18220.86
1430  UPI01431                18019.58
3809  UPI03810                17707.12

## Question 23
**What is the distribution of total_monthly_spend?**

In [30]:
df['total_monthly_spend'].describe()

count      5000.000000
mean      69926.961856
std      102386.040608
min         100.000000
25%       13757.080000
50%       35892.485000
75%       78350.982500
max      900000.000000
Name: total_monthly_spend, dtype: float64

## Question 24
**Which users have the highest total monthly spending?**

In [33]:
df.nlargest(10,"total_monthly_spend")[["user_id","total_monthly_spend"]]

       user_id  total_monthly_spend
2099  UPI02100            900000.00
3758  UPI03759            900000.00
4907  UPI04908            900000.00
2037  UPI02038            868849.19
685   UPI00686            859324.54
1981  UPI01982            844171.60
289   UPI00290            832306.30
2036  UPI02037            815972.77
1137  UPI01138            812219.61
130   UPI00131            800263.43

## Question 25
**How is monthly_transaction_count related to total_monthly_spend?**

In [35]:
df[["monthly_transaction_count","total_monthly_spend"]].corr()

                           monthly_transaction_count  total_monthly_spend
monthly_transaction_count                   1.000000             0.307182
total_monthly_spend                         0.307182             1.000000

## Question 26
**How is avg_transaction_amount related to total_monthly_spend?**

In [36]:
df[['avg_transaction_amount','total_monthly_spend']].corr()

                        avg_transaction_amount  total_monthly_spend
avg_transaction_amount                1.000000             0.700924
total_monthly_spend                   0.700924             1.000000

## Question 27
**Which users make frequent transactions with relatively small transaction amounts?**

In [39]:
df.assign(score=df.monthly_transaction_count/df.avg_transaction_amount).nlargest(10,'score')[['user_id','score']]

       user_id      score
2008  UPI02009  12.350000
2779  UPI02780  12.050000
4357  UPI04358  10.900000
2083  UPI02084   8.575000
3450  UPI03451   7.827957
2073  UPI02074   7.765057
254   UPI00255   7.700000
3830  UPI03831   7.550000
2371  UPI02372   7.350000
3085  UPI03086   7.200000

## Question 28
**Which users make fewer transactions but have high average transaction amounts?**

In [41]:
df.assign(score=df.avg_transaction_amount/df.monthly_transaction_count).nlargest(10,"score")[["user_id","score"]]

       user_id    score
4916  UPI04917  4133.28
2758  UPI02759  3699.61
2486  UPI02487  2999.04
359   UPI00360  2893.08
642   UPI00643  2427.31
4291  UPI04292  2057.23
256   UPI00257  1971.51
1591  UPI01592  1905.09
4634  UPI04635  1859.54
3301  UPI03302  1800.47

## Question 29
**Which users have a large difference between their average and maximum transaction amounts?**

In [42]:
df.assign(diff=df.max_transaction_amount - df.avg_transaction_amount).nlargest(10,"diff")[["user_id","diff"]]

       user_id      diff
2201  UPI02202  17425.27
4294  UPI04295  15466.48
708   UPI00709  15155.93
2811  UPI02812  14646.57
4024  UPI04025  14477.01
4579  UPI04580  14366.65
2129  UPI02130  13524.24
2747  UPI02748  13479.97
1019  UPI01020  13259.09
1430  UPI01431  12886.06

## Question 30
**How is avg_balance_before_txn related to average transaction amount and total monthly spending?**

In [43]:
df[['avg_balance_before_txn','avg_transaction_amount','total_monthly_spend']].corr()

,avg_balance_before_txn,avg_transaction_amount,total_monthly_spend
avg_balance_before_txn,1.000000,0.621567,0.900580
avg_transaction_amount,0.621567,1.000000,0.700924
total_monthly_spend,0.900580,0.700924,1.000000

## Question 31
**What proportion of transactions is made with merchants?**

In [44]:
df['merchant_txn_ratio'].mean()

np.float64(0.6189212)

## Question 32
**What proportion of transactions consists of peer-to-peer transfers?**

In [45]:
df['peer_txn_ratio'].mean()

np.float64(0.3818176)

## Question 33
**Which users are primarily merchant-transaction users?**

In [46]:
df.nlargest(10,'merchant_txn_ratio')[['user_id','merchant_txn_ratio']]

       user_id  merchant_txn_ratio
666   UPI00667               0.959
1068  UPI01069               0.959
729   UPI00730               0.958
1709  UPI01710               0.958
1854  UPI01855               0.958
1858  UPI01859               0.958
1967  UPI01968               0.958
2796  UPI02797               0.958
2921  UPI02922               0.958
4239  UPI04240               0.958

## Question 34
**Which users are primarily peer-to-peer transaction users?**

In [47]:
df.nlargest(10,'peer_txn_ratio')[['user_id','peer_txn_ratio']]

       user_id  peer_txn_ratio
33    UPI00034            0.85
289   UPI00290            0.85
863   UPI00864            0.85
1056  UPI01057            0.85
1183  UPI01184            0.85
1849  UPI01850            0.85
2257  UPI02258            0.85
2360  UPI02361            0.85
2599  UPI02600            0.85
2734  UPI02735            0.85

## Question 35
**Which users have a balanced combination of merchant and peer transactions?**

## Question 36
**How does total monthly spending differ between merchant-focused and peer-focused users?**

## Question 37
**How is merchant_count_month related to merchant_txn_ratio?**

In [48]:
df[['merchant_count_month','merchant_txn_ratio']].corr()

                      merchant_count_month  merchant_txn_ratio
merchant_count_month              1.000000            0.370933
merchant_txn_ratio                0.370933            1.000000

## Question 38
**How is peer_count_month related to peer_txn_ratio?**

In [49]:
df[['peer_count_month','peer_txn_ratio']].corr()

                  peer_count_month  peer_txn_ratio
peer_count_month          1.000000        0.205276
peer_txn_ratio            0.205276        1.000000

## Question 39
**Which users have the highest number of failed transactions?**

In [53]:
df.nlargest(10,'failed_transactions')[['user_id','failed_transactions']]

       user_id  failed_transactions
3627  UPI03628                   39
3849  UPI03850                   37
2108  UPI02109                   36
898   UPI00899                   35
4230  UPI04231                   35
1025  UPI01026                   34
2294  UPI02295                   34
3936  UPI03937                   34
4466  UPI04467                   34
1056  UPI01057                   33

## Question 40
**Which users have the highest failed_txn_ratio?**

In [54]:
df.nlargest(10,'failed_txn_ratio')[['user_id','failed_txn_ratio']]

      user_id  failed_txn_ratio
18   UPI00019              0.35
22   UPI00023              0.35
33   UPI00034              0.35
35   UPI00036              0.35
73   UPI00074              0.35
74   UPI00075              0.35
83   UPI00084              0.35
91   UPI00092              0.35
110  UPI00111              0.35
135  UPI00136              0.35

## Question 41
**Which users have the highest number of refund requests?**

In [56]:
df.nlargest(10,'refund_requests')[['user_id','refund_requests']]

       user_id  refund_requests
4537  UPI04538               20
867   UPI00868               19
4522  UPI04523               16
130   UPI00131               15
2457  UPI02458               15
2989  UPI02990               15
3026  UPI03027               15
4230  UPI04231               15
4436  UPI04437               15
4518  UPI04519               15

## Question 42
**How is refund_ratio related to failed_txn_ratio?**

In [57]:
df[['refund_ratio','failed_txn_ratio']].corr()

                  refund_ratio  failed_txn_ratio
refund_ratio          1.000000          0.459944
failed_txn_ratio      0.459944          1.000000

## Question 43
**Do users with high failed-transaction ratios also show higher spending volatility?**

In [59]:
df[['failed_txn_ratio','spend_volatility']].corr()

                  failed_txn_ratio  spend_volatility
failed_txn_ratio          1.000000          0.192802
spend_volatility          0.192802          1.000000

## Question 44
**Which users have unusually high suspicious_activity_score values?**

In [60]:
df.nlargest(10,'suspicious_activity_score')[['user_id','suspicious_activity_score']]

      user_id  suspicious_activity_score
18   UPI00019                      100.0
73   UPI00074                      100.0
110  UPI00111                      100.0
150  UPI00151                      100.0
186  UPI00187                      100.0
232  UPI00233                      100.0
286  UPI00287                      100.0
288  UPI00289                      100.0
320  UPI00321                      100.0
400  UPI00401                      100.0

## Question 45
**How is suspicious activity related to night-time transactions, failed transactions and refunds?**

In [62]:
df[['suspicious_activity_score','night_txn_ratio','failed_txn_ratio','refund_ratio']].corr()

,suspicious_activity_score,night_txn_ratio,failed_txn_ratio,refund_ratio
suspicious_activity_score,1.000000,0.517511,0.880752,0.572992
night_txn_ratio,0.517511,1.000000,0.254856,0.202212
failed_txn_ratio,0.880752,0.254856,1.000000,0.459944
refund_ratio,0.572992,0.202212,0.459944,1.000000

## Question 46
**Which users conduct a high proportion of their transactions at night or on weekends?**

In [64]:
df.nlargest(10,'night_txn_ratio')[['user_id','night_txn_ratio','weekend_txn_ratio']]

       user_id  night_txn_ratio  weekend_txn_ratio
3362  UPI03363            0.778              0.500
2335  UPI02336            0.777              0.588
4085  UPI04086            0.777              0.555
1000  UPI01001            0.776              0.525
4231  UPI04232            0.776              0.611
3459  UPI03460            0.774              0.396
2954  UPI02955            0.773              0.341
1788  UPI01789            0.771              0.331
1043  UPI01044            0.770              0.640
4573  UPI04574            0.770              0.352

## Question 47
**How are session_count and app_open_frequency related?**

In [65]:
df[['session_count','app_open_frequency']].corr()

                    session_count  app_open_frequency
session_count            1.000000            0.925295
app_open_frequency       0.925295            1.000000

## Question 48
**Which users open the application frequently but complete relatively few transactions?**

In [66]:
df.assign(diff=df.app_open_frequency-df.monthly_transaction_count).nlargest(10,'diff')[['user_id','diff']]

       user_id  diff
421   UPI00422   259
3560  UPI03561   229
4668  UPI04669   227
867   UPI00868   224
876   UPI00877   220
400   UPI00401   215
4634  UPI04635   212
1846  UPI01847   201
3352  UPI03353   199
3833  UPI03834   196

## Question 49
**How does cashback usage relate to merchant transactions, transaction frequency and monthly spending?**

In [67]:
df[['cashback_usage_ratio','merchant_txn_ratio','monthly_transaction_count','total_monthly_spend']].corr()

,cashback_usage_ratio,merchant_txn_ratio,monthly_transaction_count,total_monthly_spend
cashback_usage_ratio,1.000000,0.746173,0.063179,0.029599
merchant_txn_ratio,0.746173,1.000000,0.074558,0.005382
monthly_transaction_count,0.063179,0.074558,1.000000,0.307182
total_monthly_spend,0.029599,0.005382,0.307182,1.000000

## Question 50
**Which users show unusual behaviour based on transaction frequency, spending, timing, failures, refunds, app engagement and suspicious-activity scores?**